### ISSUE TITLE
A new camouflaged object detection paper

### ISSUE THREAD

**Issue by lwpyh** [visionxiang/awesome-camouflaged-object-detection#2]
Hi there,

 We just release a new paper on camouflaged object detection accepted by AAAI 2024, here is our github page: https://github.com/jyLin8100/GenSAM/, could you append it in the list?

Thanks!

**Comment by visionxiang** [comment]
OK, sure.

Good work, congrats!



lwpyh ***@***.***> 于2023年12月14日周四 05:05写道：
